#!/bin/bash
# beware that slashs have to be escaped
YOURCOMPANY="blablub"
CERT_COMPANYNAME="blablub llc"
CERT_COUNTRY="BL"
CERT_LOCALITY="blub"
CERT_PROVINCE="bla"
LOGGINGFILE="\/some\/path\/to\/logs"
DOWNLOADURL="\/path\/where\/you\/host\/the\/mlaps\/client\/file"
PATHTOWHEREYOURDOCKERIMAGELIVES="bla"
BASEPRODUCTIONPATHTOKEYCLOAK="blub"
SUPPORTPATH="\/var\/root\/Library\/Application Support"

#YOURCOMPANY
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" docker/nginx/mlaps.conf
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" docker/keycloak/dev.json
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" docker/vault/setup.sh
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" app/secrets-dev.json
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" app/starter.py
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" linux_test.sh
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" mlaps_client.sh
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" dev_enroll.sh
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" client_install.sh
sed -i -- "s/\$YOURCOMPANY/$YOURCOMPANY/g" docker-compose.base.yml
#CERT_COMPANYNAME
sed -i -- "s/\$CERT_COMPANYNAME/$CERT_COMPANYNAME/g" docker/vault/setup.sh
#CERT_COUNTRY
sed -i -- "s/\$CERT_COUNTRY/$CERT_COUNTRY/g" docker/vault/setup.sh
sed -i -- "s/\$CERT_COUNTRY/$CERT_COUNTRY/g" mlaps_client.sh
sed -i -- "s/\$CERT_COUNTRY/$CERT_COUNTRY/g" dev_enroll.sh
sed -i -- "s/\$CERT_COUNTRY/$CERT_COUNTRY/g" linux_test.sh
#CERT_LOCALITY
sed -i -- "s/\$CERT_LOCALITY/$CERT_LOCALITY/g" docker/vault/setup.sh
#CERT_PROVINCE
sed -i -- "s/\$CERT_PROVINCE/$CERT_PROVINCE/g" docker/vault/setup.sh
#LOGGINGFILE
sed -i -- "s/\$LOGGINGFILE/$LOGGINGFILE/g" client_install.sh
sed -i -- "s/\$LOGGINGFILE/$LOGGINGFILE/g" mlaps_client.sh
sed -i -- "s/\$LOGGINGFILE/$LOGGINGFILE/g" dev_enroll.sh
sed -i -- "s/\$LOGGINGFILE/$LOGGINGFILE/g" linux_test.sh
#DOWNLOADURL
sed -i -- "s/\$DOWNLOADURL/$DOWNLOADURL/g" client_install.sh
#PATHTOWHEREYOURDOCKERIMAGELIVES
sed -i -- "s/\$PATHTOWHEREYOURDOCKERIMAGELIVES/$PATHTOWHEREYOURDOCKERIMAGELIVES/g" docker/mlaps/mlaps-prod.Dockerfile
#BASEPRODUCTIONPATHTOKEYCLOAK
sed -i -- "s/\$BASEPRODUCTIONPATHTOKEYCLOAK/$BASEPRODUCTIONPATHTOKEYCLOAK/g" app/config.ini
#SUPPORTPATH
sed -i -- "s/\$SUPPORTPATH/$SUPPORTPATH/g" mlaps_client.sh
sed -i -- "s/\$SUPPORTPATH/$SUPPORTPATH/g" dev_enroll.sh
