name: "Build Container Image"
on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Check out code

      - name: Apply findAndReplaceMe file
      - run: ./findAndReplaceMe

      - uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx

      - uses: docker/login-action@v3
      - name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
      - name: Docker metadata - Main
        id: meta-main
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=snapshot,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr

      - uses: docker/build-push-action@v3
      - name: Image - Main
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          file: docker/mlaps/mlaps.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}

